### ISSUE TITLE
Sheets Quickstart fails due to NoMethodError

### ISSUE THREAD

**Issue by hashedhyphen** [gsuitedevs/ruby-samples#3]
When I ran Sheets API's Quickstart, I encountered the error below.

```
hash@hh-mbp ~/w/google-sheets-api-sample> ruby quickstart.rb
Name, Major:
Traceback (most recent call last):
quickstart.rb:48:in `<main>': undefined method `each_values' for #<Google::Apis::SheetsV4::ValueRange:0x00007fb11c1f1dd0> (NoMethodError)
```

**Comment by hashedhyphen** [comment]
I submitted CLA just a few minutes ago, and I created a PR for this issue. 

I'd be glad that you merge this PR if there are no problems 🍪

**Comment by hashedhyphen** [comment]
Now the relevant PR was merged, so I'll close this issue. Thanks :tea:

**Comment by SchmidtyApps** [comment]
@hashedhyphen it appears as if this issue has popped up again. The code in master is calling `response.each_value` again instead of `response.values.each` on line 51.

https://github.com/gsuitedevs/ruby-samples/blob/master/sheets/quickstart/quickstart.rb

**Comment by hashedhyphen** [comment]
@grant It seems this issue is caused by the commit https://github.com/gsuitedevs/ruby-samples/commit/ec561977b79c48f73c3fba77139e404251777fde#diff-63afab8a1f801a8eb06ca639724fa587

What is the purpose of that change?

**Comment by grant** [comment]
I believe this was a rubocop lint error at the time of change.
Can you state the ruby version and client library version?

https://apidock.com/ruby/Hash/each_value

**Comment by erickoledadevrel** [comment]
It looks like @grant reverted the fix in 06ee87f4f55116252ecef445970678e51f2ef3e0.

@sqrrrl - As someone that knows Ruby well, do you know what's happening here? Is the confusion here because

**Comment by erickoledadevrel** [comment]
Likely just an accidental revert, @grant rolled the fix forward. Thanks for catching this!
